/**
 * PDF Export Utilities for Trading Journal
 * 
 * All exports are now powered by jsPDF + jspdf-autotable.
 * This module re-exports from export-utils.ts for backward compatibility.
 */

export type {
  Trade as TradeForCSV,
  JournalEntry as JournalEntryForPDF,
  Analytics,
} from '@/lib/export-utils'

export {
  exportJournalToPDF,
  exportTradesToCSV,
  exportJournalToCSV,
  exportAllDataAsJSON,
  exportToPDF,
  exportTaxReportPDF,
  type Trade,
  type JournalEntry,
} from '@/lib/export-utils'

/**
 * Print journal entries (opens a new window with styled HTML)
 */
export function printJournal(entries: { id: string; title: string; content: string; mood?: string | null; market_condition?: string | null; created_at: string }[]) {
  if (entries.length === 0) return

  const now = new Date()
  const dateRange = entries.length > 0
    ? `${new Date(entries[entries.length - 1].created_at).toLocaleDateString('id-ID', { day: 'numeric', month: 'short', year: 'numeric' })} — ${new Date(entries[0].created_at).toLocaleDateString('id-ID', { day: 'numeric', month: 'short', year: 'numeric' })}`
    : now.toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' })

  const entriesHtml = entries.map((entry) => `
    <div style="margin-bottom: 24px; padding: 16px; border: 1px solid #e5e7eb; border-radius: 8px; page-break-inside: avoid;">
      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;">
        <h3 style="font-size: 16px; font-weight: 700; margin: 0; color: #1a1a2e;">${entry.title}</h3>
        <span style="font-size: 12px; color: #6b7280;">${new Date(entry.created_at).toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' })}</span>
      </div>
      <div style="display: flex; gap: 8px; margin-bottom: 12px;">
        ${entry.mood ? `<span style="display: inline-block; padding: 2px 10px; border-radius: 9999px; font-size: 12px; font-weight: 500; background: ${entry.mood === 'confident' ? '#d1fae5' : entry.mood === 'anxious' ? '#fee2e2' : '#dbeafe'}; color: ${entry.mood === 'confident' ? '#065f46' : entry.mood === 'anxious' ? '#991b1b' : '#1d4ed8'};">${entry.mood}</span>` : ''}
        ${entry.market_condition ? `<span style="display: inline-block; padding: 2px 10px; border-radius: 9999px; font-size: 12px; font-weight: 500; background: #dbeafe; color: #2563eb;">${entry.market_condition}</span>` : ''}
      </div>
      <p style="font-size: 13px; line-height: 1.6; color: #374151; white-space: pre-wrap; margin: 0;">${entry.content}</p>
    </div>
  `).join('')

  const html = `<!DOCTYPE html>
  <html>
  <head>
    <title>LuxTrade Journal — Print</title>
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body {
        font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
        background: #ffffff;
        color: #1a1a2e;
        padding: 24px;
        max-width: 800px;
        margin: 0 auto;
      }
      .header {
        text-align: center;
        margin-bottom: 32px;
        padding-bottom: 16px;
        border-bottom: 2px solid #2563eb;
      }
      .header h1 { font-size: 24px; color: #1a1a2e; margin-bottom: 4px; }
      .header .date { font-size: 14px; color: #6b7280; }
      .header .count { font-size: 12px; color: #9ca3af; margin-top: 4px; }
      .footer {
        text-align: center; margin-top: 32px; padding-top: 12px;
        border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af;
      }
      @media print {
        body { padding: 0; }
      }
    </style>
  </head>
  <body>
    <div class="header">
      <h1>LuxTrade Journal</h1>
      <div class="date">${dateRange}</div>
      <div class="count">${entries.length} entries</div>
    </div>
    ${entriesHtml}
    <div class="footer">Generated by LuxTrade — ${now.toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' })}</div>
  </body>
  </html>`

  const printWindow = window.open('', '_blank')
  if (printWindow) {
    printWindow.document.write(html)
    printWindow.document.close()
    printWindow.onload = () => {
      printWindow.print()
      printWindow.onafterprint = () => printWindow.close()
    }
  }
}
