'use client'

import { useEffect } from 'react'

/**
 * Service Worker Registration Component
 *
 * Registers the service worker generated by @serwist/next at build time.
 * This ensures PWABuilder and browsers can detect the SW on page load.
 *
 * - In production: registers /sw.js (generated by serwist during build)
 * - In development: skips registration (serwist disable: true in dev)
 */
export default function ServiceWorkerRegistration() {
  useEffect(() => {
    if (typeof window === 'undefined') return
    if (!('serviceWorker' in navigator)) return

    // Skip in development — serwist is disabled in dev mode
    if (process.env.NODE_ENV === 'development') {
      console.log('[SW] Skipped registration in development mode')
      return
    }

    const registerSW = async () => {
      try {
        const registration = await navigator.serviceWorker.register('/sw.js', {
          scope: '/',
          updateViaCache: 'none',
        })

        console.log('[SW] Registered successfully, scope:', registration.scope)

        // Listen for updates
        registration.addEventListener('updatefound', () => {
          const newWorker = registration.installing
          if (!newWorker) return

          newWorker.addEventListener('statechange', () => {
            if (newWorker.state === 'activated') {
              // New SW activated — optionally notify user to refresh
              console.log('[SW] New service worker activated')
            }
          })
        })

        // Check for updates periodically (every 60 minutes)
        setInterval(() => {
          registration.update().catch(() => {})
        }, 60 * 60 * 1000)

      } catch (error) {
        console.error('[SW] Registration failed:', error)
      }
    }

    // Register after page loads to avoid blocking rendering
    if (document.readyState === 'complete') {
      registerSW()
    } else {
      window.addEventListener('load', registerSW)
    }
  }, [])

  return null
}
