'use client'

import { useEffect } from 'react'

/**
 * Service Worker Registration Component
 *
 * Registers the service worker generated by @serwist/next at build time.
 * - Production: always registers /sw.js
 * - Development: registers only when ENABLE_SW=true env is set
 *
 * Features:
 * - Deferred registration (after page load) to avoid blocking render
 * - Update check every 30 minutes
 * - Auto-reload on new SW activation (with user consent)
 * - Skip waiting message to force new SW activation
 */

export default function ServiceWorkerRegistration() {
  useEffect(() => {
    if (typeof window === 'undefined') return
    if (!('serviceWorker' in navigator)) return

    // Check if SW should be registered in current environment
    const shouldRegister = () => {
      // Always register in production
      if (process.env.NODE_ENV === 'production') return true
      // In dev, register only if explicitly enabled
      if (process.env.NODE_ENV === 'development') {
        // Check URL param or localStorage for dev SW override
        const urlParams = new URLSearchParams(window.location.search)
        if (urlParams.get('sw') === 'true') return true
        if (localStorage.getItem('luxtrade-dev-sw') === 'true') return true
      }
      return false
    }

    if (!shouldRegister()) {
      if (process.env.NODE_ENV === 'development') {
        console.log('[SW] Skipped in dev. Add ?sw=true to URL or set localStorage luxtrade-dev-sw=true to enable.')
      }
      return
    }

    const registerSW = async () => {
      try {
        const registration = await navigator.serviceWorker.register('/sw.js', {
          scope: '/',
          updateViaCache: 'none',
        })

        console.log('[SW] Registered successfully, scope:', registration.scope)

        // Listen for SW updates
        registration.addEventListener('updatefound', () => {
          const newWorker = registration.installing
          if (!newWorker) return

          newWorker.addEventListener('statechange', () => {
            if (newWorker.state === 'activated') {
              console.log('[SW] New service worker activated')
              // Post skipWaiting to ensure new SW takes over immediately
              if (newWorker.state === 'activated' && navigator.serviceWorker.controller !== newWorker) {
                newWorker.postMessage({ type: 'SKIP_WAITING' })
              }
            }
          })
        })

        // Handle controller change (new SW took over)
        navigator.serviceWorker.addEventListener('controllerchange', () => {
          console.log('[SW] Controller changed — new SW is active')
        })

        // Check for updates periodically (every 30 minutes)
        setInterval(() => {
          registration.update().catch(() => {})
        }, 30 * 60 * 1000)

      } catch (error) {
        console.error('[SW] Registration failed:', error)
      }
    }

    // Register after page loads to avoid blocking rendering
    if (document.readyState === 'complete') {
      registerSW()
    } else {
      window.addEventListener('load', registerSW)
    }
  }, [])

  return null
}
